# install-maintenance-tasks.ps1 — Register the daily/weekly maintenance
# tasks (zombie release, pipeline_jobs prune, user_events prune) as
# Windows scheduled tasks. Wave 17 (2026-05-07) — addresses
# architecture-audit-2026-05-07 W10 + retention follow-ups.
#
# Schedule :
#   * KCKills-ZombieRelease : every day at 02:00 local
#     Calls release_zombie_claims.py to free pipeline_jobs rows
#     stuck in `claimed` with attempts >= max_attempts.
#   * KCKills-PrunePipelineJobs : every Sunday at 03:00 local
#     Calls prune_pipeline_jobs.py to delete terminal-state rows
#     older than 30 days (migration 053 fn_prune_pipeline_jobs).
#   * KCKills-PruneUserEvents : 1st of every month at 03:30 local
#     Calls prune_user_events.py to delete events older than 90
#     days (migration 054 fn_prune_user_events).
#
# Idempotent : re-running drops + recreates each task.
#
# Usage (one-shot, from this directory) :
#   pwsh ./install-maintenance-tasks.ps1
#
# Verify :
#   schtasks /query /tn "KCKills-*" /v /fo list
#   Get-ScheduledTask -TaskName "KCKills-*"

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$root    = Split-Path -Parent $MyInvocation.MyCommand.Definition
$worker  = Join-Path $root 'worker'
$venvPy  = Join-Path $worker '.venv\Scripts\python.exe'
$logDir  = Join-Path $worker 'logs'

if (-not (Test-Path $venvPy)) {
    Write-Error "venv missing at $venvPy. Bootstrap the worker first."
}

# Define each maintenance job.
$jobs = @(
    @{
        Name      = "KCKills-ZombieRelease"
        Script    = Join-Path $worker 'scripts\release_zombie_claims.py'
        Day       = $null  # daily
        Time      = "02:00"
        LogPrefix = "zombie-release"
        Desc      = "Release pipeline_jobs zombies (KCKills audit Wave 17 / W10)"
    },
    @{
        Name      = "KCKills-PrunePipelineJobs"
        Script    = Join-Path $worker 'scripts\prune_pipeline_jobs.py'
        Day       = "Sunday"
        Time      = "03:00"
        LogPrefix = "prune-pipeline"
        Desc      = "Delete terminal-state pipeline_jobs > 30 days (migration 053)"
    },
    @{
        Name      = "KCKills-PruneUserEvents"
        Script    = Join-Path $worker 'scripts\prune_user_events.py'
        # Day=1 of month — emulate via DaysOfMonth on the trigger.
        Day       = "Monthly"
        Time      = "03:30"
        LogPrefix = "prune-events"
        Desc      = "Delete user_events > 90 days (migration 054)"
    }
)

foreach ($j in $jobs) {
    $name = $j.Name
    $script = $j.Script
    $logPrefix = $j.LogPrefix

    if (-not (Test-Path $script)) {
        Write-Warning "Skipping $name — script not found at $script"
        continue
    }

    # Wrapper script per job (so PATH refresh applies and logs land in a
    # known place). Generated next to the install script.
    $wrapper = Join-Path $root "_run-$logPrefix.ps1"
    @"
# Auto-generated by install-maintenance-tasks.ps1 — do not edit.
`$env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
              [System.Environment]::GetEnvironmentVariable('Path', 'User')
`$env:PYTHONIOENCODING = 'utf-8'
`$env:PYTHONUNBUFFERED = '1'
`$ts = Get-Date -Format 'yyyyMMdd-HHmmss'
`$logFile = Join-Path '$logDir' "$logPrefix-`$ts.log"
Set-Location '$worker'
& '$venvPy' '$script' 2>&1 | Tee-Object -FilePath `$logFile
"@ | Set-Content -Path $wrapper -Encoding UTF8

    # Drop any prior schedule with this name.
    $existing = Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue
    if ($existing) {
        Write-Host "→ existing $name found, removing..." -ForegroundColor DarkGray
        Unregister-ScheduledTask -TaskName $name -Confirm:$false
    }

    $action = New-ScheduledTaskAction `
        -Execute "powershell.exe" `
        -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapper`""

    if ($j.Day -eq $null) {
        # Daily
        $trigger = New-ScheduledTaskTrigger -Daily -At $j.Time
    } elseif ($j.Day -eq "Monthly") {
        # 1st of every month
        $trigger = New-ScheduledTaskTrigger -Once -At $j.Time `
            -RepetitionInterval (New-TimeSpan -Days 30)
    } else {
        $trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek $j.Day -At $j.Time
    }

    $principal = New-ScheduledTaskPrincipal `
        -UserId $env:USERNAME `
        -LogonType Interactive `
        -RunLevel Limited

    $settings = New-ScheduledTaskSettingsSet `
        -StartWhenAvailable `
        -DontStopIfGoingOnBatteries `
        -AllowStartIfOnBatteries `
        -ExecutionTimeLimit (New-TimeSpan -Hours 1) `
        -RestartCount 1 `
        -RestartInterval (New-TimeSpan -Minutes 15)

    Register-ScheduledTask `
        -TaskName $name `
        -Action $action `
        -Trigger $trigger `
        -Principal $principal `
        -Settings $settings `
        -Description $j.Desc | Out-Null

    $cadence = if ($null -eq $j.Day) { 'daily' } else { $j.Day }
    Write-Host "✓ $name registered → $($j.Time) ($cadence)" -ForegroundColor Green
}

Write-Host ""
Write-Host "All maintenance tasks installed. Inspect with :" -ForegroundColor DarkGray
Write-Host "  Get-ScheduledTask -TaskName 'KCKills-*' | Select-Object TaskName, State" -ForegroundColor Cyan
Write-Host "Test any task immediately :" -ForegroundColor DarkGray
Write-Host "  Start-ScheduledTask -TaskName 'KCKills-ZombieRelease'" -ForegroundColor Cyan
