# install-backup-task.ps1 — Register the Supabase backup as a Windows
# scheduled task. Wave 14 (2026-05-07) — addresses architecture audit
# STOP item #1 (no scheduled backups).
#
# Schedule : Sunday 04:00 local time (UTC alignment varies by your TZ ;
# adjust if you want exact UTC). KC matches never run Sunday ~04:00 so
# the pg_dump connection load is harmless.
#
# Idempotent : if a task with the same name already exists, this
# script unregisters and recreates it.
#
# Usage (one-shot, from this directory) :
#   pwsh ./install-backup-task.ps1
#
# Verify after :
#   schtasks /query /tn "KCKills-WeeklyBackup" /v /fo list
#   Get-ScheduledTaskInfo -TaskName "KCKills-WeeklyBackup"
#
# Manual trigger to test :
#   Start-ScheduledTask -TaskName "KCKills-WeeklyBackup"
#   Get-Content "$env:USERPROFILE\Kckills\worker\logs\backup-*.log" -Tail 30

[CmdletBinding()]
param(
    [string] $TaskName = "KCKills-WeeklyBackup",
    [string] $Time     = "04:00",   # local time
    [string] $DayOfWeek = "Sunday"
)

$ErrorActionPreference = 'Stop'

$root    = Split-Path -Parent $MyInvocation.MyCommand.Definition
$worker  = Join-Path $root 'worker'
$venvPy  = Join-Path $worker '.venv\Scripts\python.exe'
$script  = Join-Path $worker 'scripts\backup_supabase.py'
$logDir  = Join-Path $worker 'logs'

if (-not (Test-Path $venvPy)) {
    Write-Error "venv missing at $venvPy. Bootstrap the worker first."
}
if (-not (Test-Path $script)) {
    Write-Error "Backup script missing at $script."
}
if (-not (Test-Path $logDir)) {
    New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}

# Wrapper script — Task Scheduler invokes a single .ps1 that handles
# logging + venv activation + PATH refresh (winget binaries aren't on
# the SYSTEM PATH that Task Scheduler inherits).
$wrapper = Join-Path $root '_run-backup.ps1'
@"
# Auto-generated by install-backup-task.ps1 — do not edit by hand.
# Refresh PATH from registry so pg_dump / aws cli are findable.
`$env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
              [System.Environment]::GetEnvironmentVariable('Path', 'User')
`$env:PYTHONIOENCODING = 'utf-8'
`$env:PYTHONUNBUFFERED = '1'
`$ts = Get-Date -Format 'yyyyMMdd-HHmmss'
`$logFile = Join-Path '$logDir' "backup-`$ts.log"
Set-Location '$worker'
& '$venvPy' '$script' 2>&1 | Tee-Object -FilePath `$logFile
"@ | Set-Content -Path $wrapper -Encoding UTF8

# Drop any prior schedule with this name so the install is idempotent.
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "→ existing task found, removing..." -ForegroundColor DarkGray
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapper`""

$trigger = New-ScheduledTaskTrigger `
    -Weekly `
    -DaysOfWeek $DayOfWeek `
    -At $Time

# Run as the current user so the venv + R2 secrets resolve correctly.
# RunLevel=Highest only if the user is admin ; LeastPrivilege otherwise.
$principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -DontStopIfGoingOnBatteries `
    -AllowStartIfOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2) `
    -RestartCount 2 `
    -RestartInterval (New-TimeSpan -Minutes 30)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description "Weekly Supabase pg_dump → R2 (KCKills audit Wave 14)"

Write-Host ""
Write-Host "✓ Task registered: $TaskName" -ForegroundColor Green
Write-Host "  Schedule  : every $DayOfWeek at $Time (local)" -ForegroundColor DarkGray
Write-Host "  Wrapper   : $wrapper" -ForegroundColor DarkGray
Write-Host "  Logs      : $logDir\backup-<ts>.log" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Test now  : Start-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Cyan
Write-Host "  Inspect   : Get-ScheduledTaskInfo -TaskName '$TaskName'" -ForegroundColor Cyan
