/**
 * Reads real KC data from src/data/kc_matches.json (generated by scripts/fetch_real_data.py).
 * Imported statically at build-time so it's baked into the bundle —
 * works on Vercel serverless without any runtime fs access.
 *
 * To refresh the data, re-run:  python scripts/fetch_real_data.py
 * which writes into /data/kc_matches.json, then copy to /web/src/data/kc_matches.json.
 */

import kcMatchesJson from "@/data/kc_matches.json";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface RealPlayer {
  name: string;
  champion: string;
  role: string;
  kills: number;
  deaths: number;
  assists: number;
  gold: number;
  cs: number;
  level: number;
}

export interface RealVod {
  provider: string;
  parameter: string;
  locale: string;
}

export interface RealGame {
  id: string;
  number: number;
  kc_players: RealPlayer[];
  opp_players: RealPlayer[];
  kc_kills: number;
  opp_kills: number;
  kc_gold: number;
  kc_towers: number;
  kc_dragons: number;
  kc_barons: number;
  vods: RealVod[];
}

export interface RealMatch {
  id: string;
  date: string;
  league: string;
  stage: string;
  kc_side: string;
  opponent: { name: string; code: string; image?: string };
  kc_image?: string;
  kc_won: boolean;
  kc_score: number;
  opp_score: number;
  best_of: number;
  games: RealGame[];
}

export interface RealData {
  generated_at: string;
  source: string;
  team: string;
  total_matches: number;
  total_games: number;
  matches: RealMatch[];
}

// ─── Data Loading ─────────────────────────────────────────────────────────────

// JSON is imported statically so it's bundled at build time. No runtime fs, no path issues.
const _data: RealData = kcMatchesJson as unknown as RealData;

export function loadRealData(): RealData {
  return _data;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Strip team prefix from player name: "KC Canna" → "Canna" */
function cleanName(name: string): string {
  // Known team prefixes
  const prefixes = ["KC ", "G2 ", "FNC ", "TH ", "GX ", "VIT ", "SK ", "MKOI ", "NAVI ", "BDS ", "SHFT ", "RGE ", "LR ", "KCB "];
  for (const p of prefixes) {
    if (name.startsWith(p)) return name.slice(p.length);
  }
  return name;
}

/** Check if a player name belongs to KC */
function isKCPlayer(name: string): boolean {
  return name.startsWith("KC ");
}

/** Map API role names to display */
export function displayRole(role: string): string {
  const map: Record<string, string> = { top: "TOP", jungle: "JGL", mid: "MID", bottom: "ADC", support: "SUP" };
  return map[role] || role.toUpperCase();
}

export function roleIcon(role: string): string {
  const icons: Record<string, string> = { top: "\u2694\uFE0F", jungle: "\uD83C\uDF3F", mid: "\u2B50", bottom: "\uD83C\uDFAF", support: "\uD83D\uDEE1\uFE0F" };
  return icons[role] || "";
}

// ─── Derived Data ─────────────────────────────────────────────────────────────

export interface RosterPlayer {
  name: string;        // clean name without prefix
  fullName: string;    // original name with prefix
  role: string;
  champions: string[];
  gamesPlayed: number;
  totalKills: number;
  totalDeaths: number;
  totalAssists: number;
}

export function getKCRoster(data: RealData): RosterPlayer[] {
  const playerMap: Record<string, RosterPlayer> = {};

  for (const match of data.matches) {
    for (const game of match.games) {
      for (const p of game.kc_players) {
        if (!isKCPlayer(p.name)) continue;

        const clean = cleanName(p.name);
        if (!playerMap[clean]) {
          playerMap[clean] = {
            name: clean,
            fullName: p.name,
            role: p.role,
            champions: [],
            gamesPlayed: 0,
            totalKills: 0,
            totalDeaths: 0,
            totalAssists: 0,
          };
        }
        const entry = playerMap[clean];
        entry.gamesPlayed++;
        entry.totalKills += p.kills;
        entry.totalDeaths += p.deaths;
        entry.totalAssists += p.assists;
        if (!entry.champions.includes(p.champion)) {
          entry.champions.push(p.champion);
        }
      }
    }
  }

  const roleOrder: Record<string, number> = { top: 0, jungle: 1, mid: 2, bottom: 3, support: 4 };
  return Object.values(playerMap).sort(
    (a, b) => (roleOrder[a.role] ?? 9) - (roleOrder[b.role] ?? 9)
  );
}

/** Get roster for a specific time period */
export function getCurrentRoster(data: RealData): RosterPlayer[] {
  // Only use 2026 matches for current roster
  const filtered: RealData = {
    ...data,
    matches: data.matches.filter((m) => m.date >= "2026-01-01"),
  };
  return getKCRoster(filtered);
}

export function getPlayerStats(data: RealData, playerName: string) {
  let kills = 0, deaths = 0, assists = 0, gamesPlayed = 0, totalGold = 0, totalCS = 0;
  const champions: Record<string, { games: number; kills: number; deaths: number; assists: number }> = {};
  const matchHistory: { matchId: string; date: string; opponent: string; champion: string; kills: number; deaths: number; assists: number; won: boolean }[] = [];

  // 🐛 2026-04-28 fix : the source data is inconsistent on player-name
  // case (e.g. "kyeahoo" lowercase vs "Canna"/"Busio"/"Yike"/"Caliste"
  // capitalised). When a user navigates to /player/Kyeahoo (the
  // capitalisation a Google search result or a manually-typed URL would
  // yield), the strict-equality match returned 0 games and the page
  // 404'd. Compare case-insensitively so canonical capitalisation works
  // regardless of how the slug was entered.
  const targetLower = playerName.toLowerCase();

  for (const match of data.matches) {
    for (const game of match.games) {
      const p = game.kc_players.find((x) => {
        const cleaned = cleanName(x.name).toLowerCase();
        return (
          cleaned === targetLower || x.name.toLowerCase() === targetLower
        );
      });
      if (!p) continue;

      gamesPlayed++;
      kills += p.kills;
      deaths += p.deaths;
      assists += p.assists;
      totalGold += p.gold;
      totalCS += p.cs;

      if (!champions[p.champion]) champions[p.champion] = { games: 0, kills: 0, deaths: 0, assists: 0 };
      champions[p.champion].games++;
      champions[p.champion].kills += p.kills;
      champions[p.champion].deaths += p.deaths;
      champions[p.champion].assists += p.assists;

      matchHistory.push({
        matchId: match.id,
        date: match.date,
        opponent: match.opponent.code,
        champion: p.champion,
        kills: p.kills,
        deaths: p.deaths,
        assists: p.assists,
        won: match.kc_won,
      });
    }
  }

  return {
    name: playerName,
    kills,
    deaths,
    assists,
    gamesPlayed,
    totalGold,
    totalCS,
    kda: deaths > 0 ? ((kills + assists) / deaths).toFixed(1) : "Perfect",
    avgKills: gamesPlayed > 0 ? (kills / gamesPlayed).toFixed(1) : "0",
    avgDeaths: gamesPlayed > 0 ? (deaths / gamesPlayed).toFixed(1) : "0",
    avgAssists: gamesPlayed > 0 ? (assists / gamesPlayed).toFixed(1) : "0",
    champions: Object.entries(champions)
      .map(([name, s]) => ({ name, ...s }))
      .sort((a, b) => b.games - a.games),
    matchHistory: matchHistory.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
  };
}

export function getTeamStats(data: RealData) {
  let totalKills = 0, totalDeaths = 0, totalGold = 0;
  let wins = 0, losses = 0;

  for (const match of data.matches) {
    if (match.kc_won) wins++;
    else losses++;
    for (const game of match.games) {
      totalKills += game.kc_kills;
      totalDeaths += game.opp_kills;
      totalGold += game.kc_gold;
    }
  }

  return { totalKills, totalDeaths, totalGold, wins, losses, totalGames: data.total_games };
}

/** Get matches sorted by date desc, optionally filtered by year */
export function getMatchesSorted(data: RealData, year?: number): RealMatch[] {
  let matches = data.matches;
  if (year) {
    matches = matches.filter((m) => m.date.startsWith(String(year)));
  }
  return [...matches].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

/** Find a match by ID */
export function getMatchById(data: RealData, matchId: string): RealMatch | undefined {
  return data.matches.find((m) => m.id === matchId);
}
