-- Migration 016 — Model evaluation lab (PR13)
--
-- Blind A/B harness for picking the right Gemini tier for descriptions.
-- Generates N descriptions per clip, one per model. User reviews them
-- side-by-side at /admin/lab and votes which is best.
--
-- The verdict drives the tier choice in worker/config.py for the
-- €45 backfill.
--
-- This table is private (admin-only RLS) — it's a tool, not user content.

CREATE TABLE IF NOT EXISTS lab_evaluations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kill_id UUID REFERENCES kills(id) NOT NULL,

    -- WHICH model produced this output
    model TEXT NOT NULL,
    media_resolution TEXT NOT NULL DEFAULT 'default'
        CHECK (media_resolution IN ('default', 'low')),

    -- WHAT the model said
    description TEXT NOT NULL,
    tags JSONB DEFAULT '[]',
    highlight_score FLOAT,
    kill_visible BOOLEAN,
    caster_hype_level INT,

    -- COST + TIMING (audit + ROI math)
    input_tokens INT,
    output_tokens INT,
    cost_usd FLOAT,
    elapsed_ms INT,

    -- USER VERDICT (filled via /admin/lab voting UI)
    user_verdict TEXT CHECK (user_verdict IN ('great','good','ok','meh','bad')),
    user_note TEXT,
    voted_at TIMESTAMPTZ,
    voted_by TEXT,                              -- email / discord id of the voter

    created_at TIMESTAMPTZ DEFAULT now()
);

-- One evaluation per (kill, model, resolution) combo. If you re-run the
-- generator with the same setup it overwrites — useful for quick
-- iteration on prompt changes without exploding the table.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_lab_eval_combo
    ON lab_evaluations(kill_id, model, media_resolution);

-- Cheap fetches for the /admin/lab page (one round-trip per kill).
CREATE INDEX IF NOT EXISTS idx_lab_eval_by_kill
    ON lab_evaluations(kill_id, model);

-- Pending-vote fetch (the page sorts these to the top).
CREATE INDEX IF NOT EXISTS idx_lab_eval_pending
    ON lab_evaluations(created_at DESC)
    WHERE user_verdict IS NULL;

-- Comments for the schema browser
COMMENT ON TABLE lab_evaluations IS
    'Blind A/B harness for picking the right Gemini tier. Generated by '
    'worker/scripts/lab_generate_evaluations.py, voted on at /admin/lab.';

COMMENT ON COLUMN lab_evaluations.model IS
    'gemini-2.5-flash-lite | gemini-2.5-pro | gemini-3-flash | gemini-3.1-pro-preview | etc';

COMMENT ON COLUMN lab_evaluations.user_verdict IS
    'Editorial rating from the lab voter. great=publish quality, '
    'good=acceptable, ok=needs polish, meh=mediocre, bad=rejected.';

-- ─── RLS ─────────────────────────────────────────────────────────────
ALTER TABLE lab_evaluations ENABLE ROW LEVEL SECURITY;

-- No public policy — service role / admin endpoints only.
